spring.application.name=Skm

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5433/skm
spring.datasource.username=postgres
spring.datasource.password=springboot

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# spring.sql.init.mode=never
# spring.jpa.defer-datasource-initialization=true